# Generated by Django 3.0.5 on 2020-05-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimages',
            name='imageURL',
            field=models.CharField(default='static/images/no-image-found.png', max_length=999),
        ),
    ]
