# Generated by Django 3.0.5 on 2020-05-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.AddField(
            model_name='order',
            name='order_file',
            field=models.CharField(blank=True, default='', max_length=2500),
        ),
    ]
