# Generated by Django 3.0.3 on 2020-05-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200504_1510'),
        ('shop', '0004_auto_20200504_1750'),
    ]

    operations = [
    ]
