# Generated by Django 3.0.5 on 2020-05-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
    ]
