# Generated by Django 3.0.3 on 2020-05-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200512_1438'),
        ('user', '0003_auto_20200512_1435'),
    ]

    operations = [
    ]
