# Generated by Django 3.0.5 on 2020-05-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200512_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
