# Generated by Django 3.0.5 on 2020-05-04 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='addr',
            new_name='address',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
