# Generated by Django 3.0.3 on 2020-05-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200511_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(default='https://i7.pngguru.com/preview/831/88/865/user-profile-computer-icons-user-interface-mystique.jpg', max_length=999),
        ),
    ]
